sched/fair: Silence compilation warning
../kernel/sched/fair.c:5411:7: warning: unused variable 'prefer_idle' [-Wunused-variable]
        bool prefer_idle = sched_feat(EAS_PREFER_IDLE) ?
             ^
../kernel/sched/fair.c:5417:6: warning: unused variable 'idle_h_nr_running' [-Wunused-variable]
        int idle_h_nr_running = idle_policy(p->policy);
            ^
../kernel/sched/fair.c:7545:16: warning: unused variable 'task_boost' [-Wunused-variable]
        unsigned long task_boost = per_task_boost(p);
                      ^
3 warnings generated.

- Instead of removing the code entirely (which may cause compilation errors),
a better solution would be to instruct the Clang compiler to suppress the warning,
as this warning message is not indicative of any real issues with the code.

Signed-off-by: mcdofrenchfreis <xyzevan@androidist.net>